apiVersion: v2
name: rq-exporter
description: A Helm chart of rq exporter. Provide prometheus metrics, alerts and dashboard.
type: application
version: 0.1.0
appVersion: v1.9.2
icon: https://artifacthub.io/static/media/placeholder_pkg_helm.png
home: https://github.com/zifter/helm-charts
sources:
  - https://github.com/zifter/helm-charts/tree/main/charts/rq-exporter
  - https://github.com/mdawar/rq-exporter
maintainers:
  - name: zifter
    email: zifter.ai+github@gmail.com
    url: https://github.com/zifter
